name: Publish to ECR
on:
  push:
    tags: ['*']
jobs:
  ecr-private:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 1800
        role-session-name: GitHubCI
        role-skip-session-tagging: true

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: ${{ secrets.ECR_PRIVATE_REPOSITORY }}

    - name: Set environment variables
      env:
        REGISTRY: ${{ secrets.ECR_PRIVATE_REPOSITORY }}
      run: |
          echo "REGISTRY=${REGISTRY}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV

    - name: Build, tag, and push manifest to Amazon ECR
      run: make all-push
